[package]
edition = "2021"
name = "render"
publish = false
version = "0.1.0"

[features]

[dependencies]
anyhow.workspace = true
arrayvec.workspace = true
bytemuck.workspace = true
common.workspace = true
components.workspace = true
ddsfile.workspace = true
egui.workspace = true
epaint.workspace = true
flume.workspace = true
glam.workspace = true
gltf.workspace = true
gpu-allocator.workspace = true
hecs.workspace = true
ktx2.workspace = true
log.workspace = true
offset-allocator.workspace = true
pacy.workspace = true
parking_lot.workspace = true
rayon.workspace = true
spin_sleep.workspace = true
spin_sleep_util.workspace = true
tracy-client.workspace = true
windows = { workspace = true, features = [
    "Wdk_System_SystemServices",
    "Win32_Graphics_CompositionSwapchain",
    "Win32_Graphics_Direct3D",
    "Win32_Graphics_Direct3D11",
    "Win32_Graphics_Direct3D12",
    "Win32_Graphics_DirectComposition",
    "Win32_Graphics_Dxgi",
    "Win32_Graphics_Dxgi_Common",
    "Win32_Graphics_Gdi",
    "Win32_Security",
    "Win32_System_Registry",
    "Win32_System_Threading",
    "Win32_System_WindowsProgramming",
] }
